@startuml
!theme spacelab
skinparam BackgroundColor #2B2B2B
skinparam linetype ortho


class DeviceEventHandler << Gameboard >> {
    + getFieldcolor = fieldcolor
    + getsize = size
    + rotate = rotate
    + validatePosition = Check if position is empty or filled
}

class GameEventListener << ASCIIRenderer >> {
    + render : render the outer frame of the board
    + fillersign : render the inner board
    + tetrisframe : render the complete board
}

class GameEventProducer << Color >> {
+ Red : getColor
+ Green : getColor
+ Blue : getColor
}

enum GameEvent <<Direction>> {
+ Down
+ Left
+ Right
}

class DeviceEventService << TileTemplate >> {
+ Templates:
+ L Template
+ S Template
+ O Template
+ I Template
}





enum Rotation {
+ DEGREE_0
+ DEGREE_90
+ DEGREE_180
+ DEGREE_270
}

GameEventProducer <-- GameEventListener
GameEventProducer o-- DeviceEventHandler
GameEventProducer --> GameEvent
GameEvent .. GameEventListener
DeviceEventService *-- DeviceEventHandler
DeviceEventHandler -- Rotation



@enduml