@startuml
'https://plantuml.com/sequence-diagram


autonumber
Player -> ArcadeGameMain: Player choose a gamemode
Size -> Gameboard: Load the actual board
Gameboard -> RenderData: Start to render the board
TileLibary -> Gameboard: Gives a random tile
Color -> Tile: Gives the tile a random color
Rotation -> Tile: Gives the tile the ability to rotate in degrees
NextTile -> Gameboard: The next tile comes into the board




@enduml